### ISSUE TITLE
Type wrapped as string

### ISSUE THREAD

**Issue by ligi** [markaren/YAJ-RPC#12]
I am having the following RPC method:

```
@RpcMethod
    fun account_list(): List<String> {
        println("accounts")
        return listOf("0xafb2f771f58513609765698f65d3f2f0224a956f")
    }
```
I would expect it to return:

`{"jsonrpc":"2.0","id":43,"result":["0xafb2f771f58513609765698f65d3f2f0224a956f"]}`

but it returns:

`{"jsonrpc":"2.0","result":"[\"0xafb2f771f58513609765698f65d3f2f0224a956f\"]","id":43.0}`

**Comment by markaren** [comment]
The result is actually a JSON object. The reason this has been done this way is that it allows complex objects to passed.

However, I see that this as little meaning when the client language is NOT Java.
I think the correct thing to do is to apply your patch (don't wrap the result as a JSON object inside the JSON payload) and rather wrap the result into JSON in JVM clients before deserializeimg them into real objects again.

**Comment by ligi** [comment]
I submitted it as a PR
